application:
  version: 2.0.0
  title: HyperMetro

hypermetro:
  file: london.json
  time: 5 # Transfer time between stations on connected lines
  table: # https://docs.spring.io/spring-shell/docs/current/api/org/springframework/shell/table/BorderStyle.html
    border: fancy_light

# Borders: fancy_light, oldschool, air, fancy_heavy